services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    depends_on:
      - postgres
      - tailscale 
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=StrongPassword123
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=YourDatabasePassword
      - KC_HOSTNAME=auth.galaxyantfarm.com
      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
      - KC_HTTP_PORT=8000
    network_mode: "service:tailscale"  # Use Tailscale network
    command: ["start-dev"]

  postgres:
    image: postgres:latest
    container_name: postgres-keycloak
    restart: unless-stopped
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=YourDatabasePassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network

  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    restart: unless-stopped
    privileged: true
    environment:
      - TS_AUTHKEY=tailscale_auth_key 
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - /var/lib/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    command: ["tailscaled"]

volumes:
  postgres_data:

networks:
  keycloak_network:
